### ISSUE TITLE
Update "proof.type" test to check if the string maps to a URL.

### ISSUE THREAD

**Issue by JSAssassin** [w3c-ccg/data-integrity-test-suite-assertion#18]
Normative statement in the spec [Verifiable Credential Data Integrity 1.0](https://www.w3.org/TR/vc-data-integrity/) published 21 Oct 2023 - The specific proof type used for the cryptographic proof MUST be specified as a string that maps to a URL.

The current test only checks if "proof.type" is a string and does not test if the string maps to a URL. https://github.com/w3c-ccg/data-integrity-test-suite-assertion/blob/main/index.js#L81-L88. How can we test this?

This is an example of what the proof and proof.type looks like:  

```
{
  type: 'DataIntegrityProof',
  created: '2022-09-27T13:29:25Z',
  verificationMethod: 'did:key:z6MkiimK73pVRzGLpj869NybZQqPTGGogmdPMmBaAHJF4uZD#z6MkiimK73pVRzGLpj869NybZQqPTGGogmdPMmBaAHJF4uZD',
  cryptosuite: 'eddsa-2022',
  proofPurpose: 'assertionMethod',
  proofValue: 'z28qVMJ9ph8DPpbK4fGoK51DYVoU1rR41T6EqZoW9AZtpUPWjWYuq94eaacGt7eSxTxna1qy1agXzT7EXUwTEsEUx'
}

// proof.type => 'DataIntegrityProof'
```

**Comment by dlongley** [comment]
@JSAssassin, checking that:

1. the context on the associated document includes the DI v2 context URL or the VC v2 context URL and that the proof type is `DataIntegrityProof`, OR
2. the context on the associated document includes the Ed25519Signature2020 context  and the proof type is `Ed25519Signature2020`

...should be sufficient for testing this.

**Comment by JSAssassin** [comment]
Addressed by https://github.com/w3c-ccg/data-integrity-test-suite-assertion/pull/22
