### ISSUE TITLE
Ability to pass a context file along in the VC generator

### ISSUE THREAD

**Issue by brianorwhatever** [w3c-ccg/data-integrity-test-suite-assertion#26]
It is right now impossible to create a VC with another context

**Comment by aljones15** [comment]
@brianorwhatever so the generation now takes an optional parameter `testVector` https://github.com/w3c-ccg/data-integrity-test-suite-assertion/blob/1f5c835edf8607d88d6e10776ebf1791828902fa/vc-generator/index.js#L22-L51

So you should be able to just provide a credential entirely now. The current API btw for the issuer and verifier tests sadly differs (clean up is needed for the functions that create the test suites), but you should be able to pass a documentLoader as a testDataOption for the vc-generator.

**Comment by aljones15** [comment]
closing as issue has been addressed.
